    description: customer resource
    get:
      is: [client-id-required]
      description: Search customers using email address, first name, last name and drivers license number. At least one search option should be provided.
      queryParameters:
           emailAddress:
             displayName: Email Address
             type: string
             description: Customer email address
             example: a@abc.com
             required: false
           firstName:
             displayName: First Name
             type: string
             description: Customer first name or given name
             example: John
             required: false
           lastName:
             displayName: Last Name
             type: string
             description: Customer last name or family name
             example: Smith
           driverLicenseNumber:
             displayName: Drivers License Number
             type: string
             description: Customer's drivers license number
             example: SMIJHN001
             required: false
           loyalityMemberNumber:
             displayName: Loyality Member Number
             type: number
             description: Loyality Member Number
             example: 213321321
             required: false
           loyalityProgramCode:
             displayName: Loyality Program Code
             type: string
             description: Loyality Program Code
             example: AC
             required: false    
      responses:
          200:
            body:    
              schema: customer
              example: !include example/customer/customers.json
          404: 
            description: No customer found in the source system for the given search criteria
            body:
              schema: error
    
    post:
      is: [client-id-required]
      description: Add or create a new customer
      body:
        schema: customer
        example: !include example/customer/newCustomer.json
      responses:
        201:
          description: A new customer is created. Use the header location url to get the new customer object.
          headers:
            location:
              description: "Relative URL of the created customer."
              type: string
              required: true
              example: /customer/123456
          body: null
    /{id}:
      get:
        is: [client-id-required]
        description: Get customer using customer Id
        responses:
          200:
            body:
              schema: customer
              example: !include example/customer/customers.json
          404: 
            description: No customer found in the source system for the given Id
            body:
              schema: error
      put:
        is: [client-id-required]
        description: Update an existing credit card object.
        body:
          application/json:
            schema: creditCard
            example: !include example/creditCard/creditCard.json
        responses:
          200:
            description: Customer updated
            body:
              application/json:
                schema: customer
                example: !include example/customer/customers.json