/carClass:
    description: check if the given SIPP code is in SIPP collection, if so retreive Car_Class Code
    get:
      is: [client-id-required]
      description: check if the given SIPP code is in SIPP collection, if so retreive Car_Class Code.
      queryParameters:  
           sippCode:
             displayName: SIPP code
             type: string
             description: The SIPP code for which Car_Class is needed
             example: "CCAR"
             required: true               
           countryCode:
             displayName: Country code
             type: string
             description: The country code to retreive correct/distinct Car_Class
             example: "GH"
             required: true
      responses:
          200:
            body:    
              #schema: flightschedule
              #example: !include example/flightschedule/flightschedulelist.json
          404: 
            description: No car class record found in the source system for the given search criteria
            body:
              schema: error

/locations:
    description: check if the given EXTENDED_OAG code is in LOC collection, if so retreive RAM_LOCATION_ID
    get:
      is: [client-id-required]
      description: check if the given EXTENDED_OAG code is in LOC collection, if so retreive RAM_LOCATION_ID.
      queryParameters:  
           oagCode:
             displayName: EXTENDED_OAG code for location
             type: string
             description: The EXTENDED_OAG code for which RAM_LOCATION_ID is needed
             example: "NGOC03"
             required: true               
      responses:
          200:
            body:    
              #schema: flightschedule
              #example: !include example/flightschedule/flightschedulelist.json
          404: 
            description: No location record found in the source system for the given search criteria
            body:
              schema: error    
              
/chargeIndicator:
    description: check if the given SOVOS_CODE is in TaxFee collection, if so retreive GDD_CODE
    get:
      is: [client-id-required]
      description: check if the given SOVOS_CODE is in TaxFee collection, if so retreive GDD_CODE.
      queryParameters:  
           sovosCode:
             displayName: SOVOS_CODE for charge type
             type: string
             description: The SOVOS_CODE for which GDD_CODE is needed
             example: "ACFR"
             required: true               
      responses:
          200:
            body:    
              #schema: flightschedule
              #example: !include example/flightschedule/flightschedulelist.json
          404: 
            description: No car class record found in the source system for the given search criteria
            body:
              schema: error                        