    description: reservation resource
    get:
      is: [client-id-required]
      description: Search reservation using reservation ID, airline, pickup location, return location. At least one search option should be provided.
      queryParameters:           
           reservationId:
             displayName: Reservation ID
             type: string
             description: The reservation ID
             example: H1232318188
             required: false
           airlineCode:
             displayName: Airline Code
             type: string
             description: The airline code used for the reservation
             example: UAL
             required: false
           pickupLocation:
             displayName: Pickup Location
             type: string
             description: The pickup location for the reservation
             example: LAX
             required: false          
      responses:
          200:
            body:    
              #schema: reservation
              example: !include example/reservation/reservations.json
          404: 
            description: No reservation found in the source system for the given search criteria
            body:
              schema: error
    /{id}:
      get:
        is: [client-id-required]
        description: Get reservation using the system Id when the reservation was pesisted
        responses:
          200:
            body:
              #schema: reservation
              example: !include example/reservation/reservation.json
          404: 
            description: No reservation was found in the system for the given Id
            body:
              schema: error              
    post:
      is: [client-id-required]
      description: Persists a reservation copy
      body:
        #schema: reservation
        example: !include example/reservation/reservation.json
      responses:
        201:
          description: A reservation copy is persisted. Use the header location url to get the persisted reservation object.
          headers:
            location:
              description: "Relative URL of the persisted reservation."
              type: string
              required: true
              example: /reservation/123456
          body: null              