    description: reservation resource
    get:
      is: [client-id-required]
      description: Search reservation using reservation ID, airline, pickup location, return location. At least one search option should be provided.
      queryParameters:
           reservationId:
             displayName: Reservation ID
             type: string
             description: The reservation ID
             example: H1232318188
             required: false
           airlineCode:
             displayName: Airline Code
             type: string
             description: The airline code used for the reservation
             example: UAL
             required: false
           pickupLocation:
             displayName: Pickup Location
             type: string
             description: The pickup location for the reservation
             example: LAX
             required: false          
      responses:
          200:
            body:    
              #schema: reservation
              example: !include example/reservation/reservations.json
          404: 
            description: No reservation found in the source system for the given search criteria
            body:
              schema: error