   description:  RMS vas resource  
   post:
      is: [client-id-required]
      description: This resource specifically deals with RMS vas.
      body: 
        application/json:

      responses: 
        200:
          body: 
            application/json:
        400:
          body:
            application/json:
        500:
          body:  
            application/json: