/oagLocation:
    description: check if the given OAG code is in LOC collection, if so retreive EXTENDED_OAG
    get:
      is: [client-id-required]
      description: check if the given OAG code is in LOC collection, if so retreive EXTENDED_OAG.
      queryParameters:  
           oagCode:
             displayName: OAG code for location
             type: string
             description: The OAG code for which EXTENDED_OAG is needed
             example: "NGO"
             required: true    
           brand:
             displayName: BRAND code to get unique location
             type: string
             description: The BRAND code for which EXTENDED_OAG is needed
             example: "Hertz"
             required: true                        
      responses:
          200:
            body:    
          404: 
            description: No record found in the source system for the given search criteria
            body:
              schema: error 
/extendedOagLocation:
    description: check if the given EXTENDED_OAG code is in LOC collection, if so retreive OAG
    get:
      is: [client-id-required]
      description: check if the given EXTENDED_OAG code is in LOC collection, if so retreive OAG.
      queryParameters:  
           extendedOagCode:
             displayName: EXTENDED_OAG code for location
             type: string
             description: The EXTENDED_OAG code for which OAG is needed
             example: "NGO"
             required: true
           brand:
             displayName: BRAND code for unique location
             type: string
             description: The BRAND code for which OAG is needed
             example: "Hertz"
             required: true             
      responses:
          200:
            body:    
          404: 
            description: No record found in the source system for the given search criteria
            body:
              schema: error
/rateTypeOta:
    description: check if the given OTA_VALUE code is in rmsvasxref collection, if so retreive GDDRateIdentification
    post:
      is: [client-id-required]
      description: check if the given OTA_VALUE code is in rmsvasxref collection, if so retreive GDDRateIdentification.
      body:
        application/json:                                       
      responses:
          200:
            body:    
          404: 
            description: No record found in the source system for the given search criteria
            body:
              schema: error     
              
/rateTypeGdd:
    description: check if the given GDDRateIdentification code is in rmsvasxref collection, if so retreive OTA_VALUE
    post:
      is: [client-id-required]
      description: check if the given GDDRateIdentification code is in rmsvasxref collection, if so retreive OTA_VALUE.
      body:
        application/json:             
      responses:
          200:
            body:    
          404: 
            description: No record found in the source system for the given search criteria
            body:
              schema: error                                    