#%RAML 1.0
title: Sys API Cosmos DB System layer API
version: 1.0
#baseUri: https://template-hertz-exp-api.cloudhub.io/api/{version}
baseUri: https://{envPrefix}-sys-api-cosmos-db-{apiVersion}.esb.hertz.com/api/
documentation: 
  - title: Hertz  Experiance API template 
    content: | 
        welcome to the Hertz API Led Approach template documentation
  - title: Getting Started
    content: !include docs/getting_started.md
mediaType: application/json
protocols: [HTTPS]

# All mule applications will have clien-id & client-secret policy enforced
traits: 
  client-id-required:
      headers:
        client_id:
          type: string
          required: true
        client_secret:
          type: string
          required: true

# below is an example for creating types.
types:  
  error:
    type: !include api/types/error/error.schema
    description: Schema describing error message
  reservation:
    type: !include api/types/reservation/reservation.schema
    description: This is the schema describing reservation  
#  flightdata:
#    type: !include api/types/flightdata/flightdata.schema
#    description: This is the schema describing flight data    

# below is an example for creating resourcetypes.
resourceTypes:
  collection:
      usage: This resource type should be used for any collection of items
      description: The collection of <<resourcePathName>>
      get:
        description: Get all <<resourcePathName>>, optionally filtered
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>
  collection-item:
      description: Entity representing a <<resourcePathName|!singularize>>
      get:
        description: Get the <<resourcePathName|!singularize>> with matching id
        responses:
          200:
            body:
              application/json:
          404:
            body:
              schema: error

/reservation: !include api/reservation.raml
/flightschedule: !include api/flightschedule.raml
/valueAddedServices: !include api/valueaddedservices.raml
/ramSync: !include api/ramsync.raml
    