    description: Credit Card resource
    post:
      is: [client-id-required]
      description: Add a new Credit Card
      body:
        application/json:
          schema: creditCard
          example: !include example/creditCard/newCreditCard.json
      responses:
        201:
          description: A new credit card is created. Use the header location url to get the new credit card object.
          headers:
            location:
              description: "Relative URL of the created credit card."
              type: string
              required: true
              example: /creditCard/12334
          body: null
    /{id}:
      get:
        is: [client-id-required]
        description: Get credit card using Id (creditCard.id = {id})
        responses:
          200:
            body:
              application/json:
                schema: creditCard
                example: !include example/creditCard/creditCard.json
          404: 
            description: No credit card found in the source system for the given Id
            body:
              schema: error
      put:
        is: [client-id-required]
        description: Update an existing credit card object.
        body:
          application/json:
            schema: creditCard
            example: !include example/creditCard/creditCard.json
        responses:
          200:
            description: Customer updated
            body:
              application/json:
                schema: creditCard
                example: !include example/creditCard/creditCard.json