    description: flightschedule resource
    get:
      is: [client-id-required]
      description: Search flight schedule using carrier code, flight number and departure date. All three parameters are required.
      queryParameters:           
           carrierCode:
             displayName: Carrier Code
             type: string
             description: The carrier code for the flight
             example: TZ
             required: true
           flightNumber:
             displayName: Flight Number
             type: string
             description: The flight number for the flight
             example: UAL
             required: true
           departureDate:
             displayName: Departure Date
             type: number
             description: The departure date for the flight
             example: 20070227
             required: true          
      responses:
          200:
            body:    
              #schema: flightschedule
              example: !include example/flightschedule/flightschedulelist.json
          404: 
            description: No flight schedule record found in the source system for the given search criteria
            body:
              schema: error
    /{id}:
      get:
        is: [client-id-required]
        description: Get flight schedule record using the system Id that was generated when the flight schedule record was pesisted
        responses:
          200:
            body:
              #schema: flightschedule
              example: !include example/flightschedule/flightschedule.json
          404: 
            description: No flight schedule record was found in the system for the given Id
            body:
              schema: error              
    post:
      is: [client-id-required]
      description: Persists a flight schedule record
      body:
        #schema: flightschedule
        example: !include example/flightschedule/flightschedule.json
      responses:
        201:
          description: A flight schedule record is persisted. Use the header location url to get the persisted flight schedule object.
          headers:
            location:
              description: Relative URL of the persisted flight schedule record
              type: string
              required: true
              example: /flightschedule/54950737
          body: null              